services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.8"
      MEMORY: "8G"
      DIFFICULTY: "normal"
      MOTD: "성용쓰의 마크서버"
      MAX_PLAYERS: "10"
      ONLINE_MODE: "TRUE"
      OPS: "soseoyo12"
      TZ: "Asia/Seoul"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_PROJECTS: |
        essentialsx
        luckperms
        coreprotect
        worldedit
        squaremap
        spark
        chunky
        viaversion
        viabackwards
    volumes:
      - ./data:/data
    restart: unless-stopped
    stdin_open: true
    tty: true
